<?php

use App\Models\CustomerInvite;
use App\Models\Machine;
use App\Models\User;
use App\Services\MondayClient;
use App\Services\MondayCustomerDirectory;
use Illuminate\Auth\Events\Registered;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rules;
use Livewire\Attributes\Layout;
use Livewire\Volt\Component;

/**
 * Customer registration.
 *
 * Three entry points, one component:
 *
 *   1. /register (no token) — show a quiet "you need an invite
 *      link" page. We do NOT allow free sign-ups because every
 *      portal customer must already be on file in the monday.com
 *      Customer Details board — that's the auth.
 *
 *   2. /register/{token} where the invite is a SNAPSHOT
 *      (is_snapshot = true) — the original flow. The token was
 *      generated by `php artisan portal:invite-customer` from a
 *      monday.com record, and the customer identity (email,
 *      account, branch, region, address) is snapshotted onto the
 *      invite. The form pre-fills those fields and locks them,
 *      so the customer can only type their own name + password
 *      + their equipment. The monday_id from the invite is used
 *      as-is.
 *
 *   3. /register/{token} where the invite is OPEN
 *      (is_snapshot = false) — the post-2026-07-01 flow. The
 *      invite is just a single-use token for an email that is
 *      NOT yet on the monday.com Customer Details board. The
 *      customer types their hospital / branch / region / address
 *      on the form, and the portal creates a new monday row on
 *      submit and links the new User to it.
 */
new #[Layout('layouts.guest')] class extends Component
{
    /**
     * The token from the URL, if any. Empty for the bare /register
     * page. Populated by Livewire from the route param.
     */
    public string $token = '';

    /**
     * Snapshot fields (locked) — come from the invite (which got
     * them from monday.com). For OPEN invites, the customer is
     * allowed to type into these fields instead.
     */
    public string $email       = '';
    public string $accountName = '';
    public string $branch      = '';
    public string $region      = '';
    public string $address     = '';

    /**
     * Customer-supplied fields.
     */
    public string $name                = '';
    public string $password            = '';
    public string $password_confirmation = '';

    /**
     * Primary machine — required. The customer must register at
     * least one machine at sign-up; this becomes the default
     * equipment in the ticket form and powers the "My machines"
     * list on their profile.
     */
    public string $primaryBrand    = '';
    public string $primaryModel    = '';
    public string $primarySerial   = '';
    public string $primaryNickname = '';

    /**
     * Secondary machine — optional. If the customer skips brand +
     * model, no second row is created.
     */
    public string $secondaryBrand    = '';
    public string $secondaryModel    = '';
    public string $secondarySerial   = '';
    public string $secondaryNickname = '';

    /**
     * Live-updated password strength: empty | weak | fair | good | strong.
     */
    public string $passwordStrength = '';

    /**
     * Set to true when the URL doesn't carry a valid token. The
     * blade uses this to swap the form for the "request an invite"
     * message.
     */
    public bool $needsInvite = false;

    /**
     * Set to true when the token is well-formed but has been used
     * or has expired. The blade shows an explanation.
     */
    public bool $inviteInvalid = false;

    public ?string $inviteInvalidReason = null;

    /**
     * True when the invite is OPEN (customer types their own
     * hospital info). False for snapshot invites (fields are
     * locked). Computed in mount() from the invite row.
     */
    public bool $isOpenInvite = false;

    /**
     * Mount: load the invite (if any) and seed the snapshot fields.
     */
    public function mount(MondayCustomerDirectory $directory): void
    {
        $token = trim($this->token);
        if ($token === '') {
            $this->needsInvite = true;
            return;
        }

        $invite = CustomerInvite::findUsable($token);
        if (! $invite) {
            $this->inviteInvalid = true;

            // Distinguish the failure mode for the user.
            $row = CustomerInvite::query()->where('token', $token)->first();
            if (! $row) {
                $this->inviteInvalidReason = 'unknown';
            } elseif ($row->isUsed()) {
                $this->inviteInvalidReason = 'used';
            } elseif ($row->isExpired()) {
                $this->inviteInvalidReason = 'expired';
            } else {
                $this->inviteInvalidReason = 'unknown';
            }
            return;
        }

        // Snapshot invites must STILL be on the monday.com
        // Customer Details board. If the customer has been
        // archived (e.g. account closed), reject the token even
        // though the snapshot row still exists. Open invites
        // skip this check — by definition the customer is not
        // on the board yet.
        if ($invite->isSnapshot()) {
            try {
                $live = $directory->findByEmail($invite->email);
            } catch (\Throwable $e) {
                // If monday is unreachable, we still allow the
                // snapshot through — better to onboard a customer
                // than to lock them out because of an API outage.
                $live = null;
            }
            if ($live === null) {
                $this->inviteInvalid      = true;
                $this->inviteInvalidReason = 'monday_missing';
                return;
            }
        }

        $this->isOpenInvite = $invite->isOpen();
        $this->email       = $invite->email;
        // For snapshot invites, the lock is on. For open invites,
        // we leave the account/branch/region/address fields empty
        // so the customer types into them.
        if ($invite->isSnapshot()) {
            $this->accountName = (string) $invite->account_name;
            $this->branch      = (string) $invite->branch;
            $this->region      = (string) ($invite->region  ?? '');
            $this->address     = (string) ($invite->address ?? '');
        }
    }

    /**
     * Handle the registration. Customer-only. TSP/manager accounts
     * are provisioned from monday.com, never via this form.
     */
    public function register(MondayClient $monday): void
    {
        \Illuminate\Support\Facades\Log::info('REGISTER_DEBUG', [
            'email' => $this->email,
            'name'  => $this->name,
            'isOpen' => isset($this->isOpenInvite) ? $this->isOpenInvite : 'unset',
            'token' => $this->token,
        ]);
        // Re-validate the token at submit time (not just at mount)
        // so a stale page doesn't bypass expiry.
        $invite = CustomerInvite::findUsable($this->token);
        if (! $invite) {
            $this->addError('token', 'This invite link is no longer valid. Please ask your service coordinator for a new one.');
            return;
        }

        // Validation rules. For open invites, the snapshot fields
        // (accountName, branch, region) are user-input and become
        // required; for snapshot invites they are locked to the
        // invite values and just need to be present.
        $rules = [
            'name'                  => ['required', 'string', 'max:255'],
            'password'              => ['required', 'string', 'confirmed', Rules\Password::defaults()],
            'email'                 => ['required', 'string', 'lowercase', 'email', 'max:191'],
            'accountName'           => [$invite->isOpen() ? 'required' : 'nullable', 'string', 'max:255'],
            'branch'                => [$invite->isOpen() ? 'required' : 'nullable', 'string', 'max:255'],
            'region'                => [$invite->isOpen() ? 'required' : 'nullable', 'string', 'max:100'],
            'address'               => ['nullable', 'string', 'max:500'],

            // Primary machine — always required (snapshot or open).
            'primaryBrand'          => ['required', 'string', 'max:120'],
            'primaryModel'          => ['required', 'string', 'max:120'],
            'primarySerial'         => ['nullable', 'string', 'max:120'],
            'primaryNickname'       => ['nullable', 'string', 'max:120'],

            // Secondary machine — only brand + model are required
            // IF the customer started filling it in. We validate
            // brand-implies-model and model-implies-brand below.
            'secondaryBrand'        => ['nullable', 'string', 'max:120'],
            'secondaryModel'        => ['nullable', 'string', 'max:120'],
            'secondarySerial'       => ['nullable', 'string', 'max:120'],
            'secondaryNickname'     => ['nullable', 'string', 'max:120'],
        ];

        $messages = [
            'email.required'             => 'Your email is missing. Please use the link your coordinator sent you.',
            'email.email'                => 'That email address looks invalid. Please contact your service coordinator.',
            'primaryBrand.required'      => 'Please tell us the brand of your primary machine (required).',
            'primaryModel.required'      => 'Please tell us the model of your primary machine (required).',
        ];

        $validated = $this->validate($rules, $messages);

        // Secondary machine: if either brand OR model is filled,
        // both must be filled. We do this after the main validate()
        // so the error message is friendly.
        $hasSecondaryBrand = trim($validated['secondaryBrand'] ?? '') !== '';
        $hasSecondaryModel = trim($validated['secondaryModel'] ?? '') !== '';
        if ($hasSecondaryBrand xor $hasSecondaryModel) {
            $this->addError(
                $hasSecondaryBrand ? 'secondaryModel' : 'secondaryBrand',
                'Please fill in both the brand and model of the second machine, or leave both blank.'
            );
            return;
        }

        // For snapshot invites, the email/accountName/branch
        // on the form must match what's on the invite — protects
        // against a tampered form.
        if ($invite->isSnapshot()) {
            if (strtolower(trim($validated['email'])) !== strtolower(trim($invite->email))) {
                $this->addError('email', 'The email on this form does not match the invite. Please use the original link.');
                return;
            }
            if (trim($validated['accountName']) !== trim($invite->account_name)) {
                $this->addError('accountName', 'The account name on this form does not match the invite. Please use the original link.');
                return;
            }
        }

        // Refuse to register an email that already has an account
        // — covers the case where two tokens were issued for the
        // same address.
        if (User::query()->where('email', $validated['email'])->exists()) {
            $this->addError('email', 'An account with this email already exists. Try signing in instead.');
            return;
        }

        // -----------------------------------------------------------------
        // Open invite: create the monday.com row FIRST. If monday
        // is down, we abort with an error on the form and do NOT
        // create a half-built local user. Snapshot invites skip
        // this — they already have a monday id.
        // -----------------------------------------------------------------
        if ($invite->isOpen()) {
            $payload = [
                'email'        => $validated['email'],
                'account_name' => $validated['accountName'],
                'branch'       => $validated['branch'],
                'region'       => $validated['region'] ?? null,
                'address'      => $validated['address'] ?? null,
            ];

            $newMondayId = $monday->createCustomerItem($payload);
            if (! $newMondayId) {
                // Surface a friendly error on the form. Don't leak
                // the raw API failure.
                $this->addError(
                    'accountName',
                    "We couldn't reach our customer records system to add your hospital. Please try again in a few minutes, or contact your service coordinator."
                );
                return;
            }

            // Cache-bust so the next /login lookup sees the new row.
            $monday->flushCache();
            $monday->cacheForget("customer:" . strtolower($validated['email']));
        }

        $validated['password']  = Hash::make($validated['password']);
        $validated['role']      = 'customer';
        $validated['status']    = 'active';
        $validated['monday_id'] = $invite->isOpen()
            ? $newMondayId
            : $invite->monday_customer_id;

        // Map camelCase form property names to snake_case DB columns
        // for User::create(). The property is $accountName but the
        // users.account_name column is snake_case.
        $user = User::create([
            'name'         => $validated['name'],
            'email'        => $validated['email'],
            'password'     => $validated['password'],
            'role'         => $validated['role'],
            'status'       => $validated['status'],
            'monday_id'    => $validated['monday_id'],
            'branch'       => $validated['branch']       ?? null,
            'region'       => $validated['region']       ?? null,
            'address'      => $validated['address']      ?? null,
            'account_name' => $validated['accountName'] ?? null,
        ]);

        // Primary machine — always present.
        Machine::create([
            'user_id'       => $user->id,
            'brand'         => $validated['primaryBrand'],
            'model'         => $validated['primaryModel'],
            'serial_number' => $validated['primarySerial']   ?: null,
            'nickname'      => $validated['primaryNickname'] ?: null,
            'is_primary'    => true,
        ]);

        // Secondary machine — only if both brand + model were filled.
        if ($hasSecondaryBrand && $hasSecondaryModel) {
            Machine::create([
                'user_id'       => $user->id,
                'brand'         => $validated['secondaryBrand'],
                'model'         => $validated['secondaryModel'],
                'serial_number' => $validated['secondarySerial']   ?: null,
                'nickname'      => $validated['secondaryNickname'] ?: null,
                'is_primary'    => false,
            ]);
        }

        // Spend the token AFTER the user is created. A failed
        // create shouldn't lock out a legitimate customer.
        $invite->markUsed($user->id);

        event(new Registered($user));
        Auth::login($user);

        $this->redirect(route($user->homeRoute(), absolute: false), navigate: true);
    }

    /**
     * React to the password-strength JS hook from the input below.
     */
    public function updatedPasswordStrength(string $value): void
    {
        $this->passwordStrength = $value;
    }
}; ?>

<div>
    @if ($needsInvite)
        {{-- ───────  Bare /register — no token  ─────── --}}
        <div class="mb-6">
            <h2 class="font-display text-2xl font-bold text-brand-navy">Create your customer account</h2>
            <p class="mt-2 text-sm text-brand-slate">
                The portal is invite-only. Your service coordinator has to add your hospital to the
                monday.com customer list and send you a registration link before you can sign up.
            </p>
        </div>

        <div class="rounded-xl bg-brand-cream/60 p-4 ring-1 ring-brand-mist/60">
            <p class="text-sm text-brand-slate">
                <span class="font-semibold text-brand-navy">Need an account?</span><br>
                Email your service coordinator and ask them to add you to the
                <span class="font-medium">Customer Details</span> board on monday.com. Once they've done that,
                they'll send you a one-time link to this page.
            </p>
        </div>

        <p class="mt-6 text-center text-sm text-brand-slate">
            {{ __('Already have an account?') }}
            <a href="{{ route('login') }}" wire:navigate
               class="font-semibold text-brand-blue hover:text-brand-blue-3 underline-offset-2 hover:underline">
                {{ __('Sign in') }}
            </a>
        </p>

    @elseif ($inviteInvalid)
        {{-- ───────  Token is dead  ─────── --}}
        <div class="mb-6">
            <h2 class="font-display text-2xl font-bold text-brand-navy">This invite link can't be used</h2>
        </div>

        <div class="rounded-xl bg-rose-50 p-4 ring-1 ring-rose-200">
            <p class="text-sm text-rose-800">
                @switch($inviteInvalidReason)
                    @case('used')
                        This invite has already been used. If you tried to sign up before but the registration didn't go through,
                        please ask your service coordinator for a fresh link.
                        @break
                    @case('expired')
                        This invite has expired. Registration links are valid for 14 days. Please ask your service coordinator to send you a new one.
                        @break
                    @case('monday_missing')
                        Your hospital is no longer listed in our customer records. Please contact your service coordinator
                        to confirm your account is still active.
                        @break
                    @default
                        We couldn't find this invite. The link may have been mistyped, or the invite was revoked.
                        Please ask your service coordinator to send you a new one.
                @endswitch
            </p>
        </div>

        <p class="mt-6 text-center text-sm text-brand-slate">
            {{ __('Already have an account?') }}
            <a href="{{ route('login') }}" wire:navigate
               class="font-semibold text-brand-blue hover:text-brand-blue-3 underline-offset-2 hover:underline">
                {{ __('Sign in') }}
            </a>
        </p>

    @else
        {{-- ───────  Token is good — show the form  ─────── --}}
        <div class="mb-6">
            <h2 class="font-display text-2xl font-bold text-brand-navy">Create your customer account</h2>
            <p class="mt-1 text-sm text-brand-slate">
                @if ($isOpenInvite)
                    Welcome! Your coordinator has invited you to the portal. Fill in your hospital details
                    and a password to finish setting up your account, and tell us about the equipment you
                    have on site.
                @else
                    We've confirmed your hospital with our records. Fill in your name, a password, and your
                    primary equipment to finish setting up your account.
                @endif
            </p>
        </div>

        <form wire:submit="register" class="space-y-5">

            {{-- ───────  Registration errors (top of form)  ─────── --}}
            {{--
                Per-field <x-input-error> covers name / password / confirmation,
                but errors on the locked snapshot fields (email, accountName,
                branch) and on the token itself have no visible anchor. Show
                them all in one banner above the form so the user always sees
                why the submit didn't go through.
            --}}
            @if ($errors->any())
                <div class="rounded-xl bg-rose-50 p-4 ring-1 ring-rose-200" role="alert" aria-live="polite">
                    <div class="flex items-start gap-3">
                        <svg class="mt-0.5 h-5 w-5 flex-none text-rose-500" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.94 6.94a1.5 1.5 0 112.12 2.12L8.94 11.18a1.5 1.5 0 11-2.12-2.12l2.12-2.12zm.31 5.06a1 1 0 112 0 1 1 0 01-2 0z" clip-rule="evenodd" />
                        </svg>
                        <div class="flex-1">
                            <p class="text-sm font-semibold text-rose-800">We couldn't create your account</p>
                            <ul class="mt-1 list-disc space-y-0.5 pl-5 text-sm text-rose-700">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                </div>
            @endif

            {{-- ───────  Account snapshot (locked)  ─────── --}}
            @if (! $isOpenInvite)
                <div class="rounded-xl bg-brand-cream/60 p-4 space-y-3 ring-1 ring-brand-mist/60">
                    <p class="text-xs font-semibold uppercase tracking-wider text-brand-blue">Your hospital</p>

                    <div class="grid grid-cols-1 gap-3 sm:grid-cols-2">
                        <div>
                            <p class="text-xs font-medium text-brand-slate">Account</p>
                            <p class="mt-0.5 text-sm font-semibold text-brand-navy">{{ $accountName }}</p>
                        </div>
                        <div>
                            <p class="text-xs font-medium text-brand-slate">Region</p>
                            <p class="mt-0.5 text-sm font-semibold text-brand-navy">{{ $region ?: '—' }}</p>
                        </div>
                        <div>
                            <p class="text-xs font-medium text-brand-slate">Branch</p>
                            <p class="mt-0.5 text-sm font-semibold text-brand-navy">{{ $branch }}</p>
                        </div>
                        <div>
                            <p class="text-xs font-medium text-brand-slate">Email</p>
                            <p class="mt-0.5 text-sm font-semibold text-brand-navy break-all">{{ $email }}</p>
                        </div>
                    </div>

                    @if ($address)
                        <div>
                            <p class="text-xs font-medium text-brand-slate">Address</p>
                            <p class="mt-0.5 text-sm text-brand-navy">{{ $address }}</p>
                        </div>
                    @endif

                    {{-- Hidden fields so Livewire carries them through validate() --}}
                    <input type="hidden" wire:model="email">
                    <input type="hidden" wire:model="accountName">
                    <input type="hidden" wire:model="branch">
                    <input type="hidden" wire:model="region">
                    <input type="hidden" wire:model="address">
                </div>
            @endif

            {{-- ───────  Customer-typed fields  ─────── --}}
            <div>
                <x-input-label for="name" :value="__('Your full name')" />
                <x-text-input wire:model="name" id="name" class="mt-2" type="text" name="name" required autofocus autocomplete="name" placeholder="Jane Doe" />
                <x-input-error :messages="$errors->get('name')" class="mt-2" />
            </div>

            <div x-data="{
                    strength: '',
                    score(pw) {
                        let s = 0;
                        if (pw.length >= 8)  s++;
                        if (pw.length >= 12) s++;
                        if (/[A-Z]/.test(pw)) s++;
                        if (/[0-9]/.test(pw)) s++;
                        if (/[^A-Za-z0-9]/.test(pw)) s++;
                        return s;
                    },
                    refresh(v) { this.strength = v; $wire.set('passwordStrength', v); }
                }">
                <x-input-label for="password" :value="__('Password')" />
                <x-text-input wire:model.live="password" id="password" class="mt-2"
                                type="password"
                                name="password"
                                required autocomplete="new-password"
                                placeholder="At least 8 characters"
                                x-on:input="refresh(
                                    ['empty','weak','fair','good','strong'][Math.min(4, score($event.target.value))]
                                )" />
                <p class="mt-1 text-xs text-brand-slate">Use at least 8 characters. Mix letters, numbers, and a symbol for a stronger password.</p>

                <div class="mt-2 flex items-center gap-2" x-show="strength && strength !== 'empty'">
                    <div class="h-1.5 flex-1 overflow-hidden rounded-full bg-brand-mist">
                        <div class="h-full transition-all"
                             :class="{
                                 'w-1/4 bg-rose-500':       strength === 'weak',
                                 'w-2/4 bg-amber-500':      strength === 'fair',
                                 'w-3/4 bg-blue-500':       strength === 'good',
                                 'w-full bg-brand-green-2': strength === 'strong',
                             }"></div>
                    </div>
                    <span class="text-xs font-medium"
                          :class="{
                              'text-rose-600':       strength === 'weak',
                              'text-amber-600':      strength === 'fair',
                              'text-blue-600':       strength === 'good',
                              'text-brand-green-2':  strength === 'strong',
                          }"
                          x-text="{
                              'weak':   'Weak',
                              'fair':   'Fair',
                              'good':   'Good',
                              'strong': 'Strong',
                          }[strength] || ''"></span>
                </div>
                <x-input-error :messages="$errors->get('password')" class="mt-2" />
            </div>

            <div>
                <x-input-label for="password_confirmation" :value="__('Confirm password')" />
                <x-text-input wire:model="password_confirmation" id="password_confirmation" class="mt-2"
                                type="password"
                                name="password_confirmation" required autocomplete="new-password" placeholder="Re-enter your password" />
                <x-input-error :messages="$errors->get('password_confirmation')" class="mt-2" />
            </div>

            {{-- ───────  Hospital details (OPEN invite only)  ─────── --}}
            @if ($isOpenInvite)
                <div class="rounded-xl bg-brand-cream/60 p-4 space-y-4 ring-1 ring-brand-mist/60">
                    <p class="text-xs font-semibold uppercase tracking-wider text-brand-blue">Your hospital</p>
                    <p class="text-xs text-brand-slate -mt-3">
                        We need these to set up your record on our customer list. After this, you'll be on
                        file for future service requests.
                    </p>

                    <div>
                        <x-input-label for="email_readonly" :value="__('Email')" />
                        <x-text-input id="email_readonly" class="mt-2" type="email" value="{{ $email }}" disabled />
                        <p class="mt-1 text-xs text-brand-slate">This is the email your coordinator invited. It can't be changed here.</p>
                    </div>

                    <div>
                        <x-input-label for="accountName" :value="__('Hospital / account name')" />
                        <x-text-input wire:model="accountName" id="accountName" class="mt-2" type="text" name="accountName" required autocomplete="organization" placeholder="e.g. St. Luke's Medical Center" />
                        <x-input-error :messages="$errors->get('accountName')" class="mt-2" />
                    </div>

                    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
                        <div>
                            <x-input-label for="region" :value="__('Region')" />
                            <x-text-input wire:model="region" id="region" class="mt-2" type="text" name="region" required autocomplete="address-level1" placeholder="e.g. NCR" />
                            <x-input-error :messages="$errors->get('region')" class="mt-2" />
                        </div>
                        <div>
                            <x-input-label for="branch" :value="__('Branch')" />
                            <x-text-input wire:model="branch" id="branch" class="mt-2" type="text" name="branch" required autocomplete="address-level2" placeholder="e.g. Quezon City" />
                            <x-input-error :messages="$errors->get('branch')" class="mt-2" />
                        </div>
                    </div>

                    <div>
                        <x-input-label for="address" :value="__('Address (optional)')" />
                        <x-text-input wire:model="address" id="address" class="mt-2" type="text" name="address" autocomplete="street-address" placeholder="Street, city, postcode" />
                        <x-input-error :messages="$errors->get('address')" class="mt-2" />
                    </div>
                </div>
            @endif

            {{-- ───────  Equipment: primary machine (required)  ─────── --}}
            <div class="rounded-xl bg-brand-cream/60 p-4 space-y-4 ring-1 ring-brand-mist/60">
                <p class="text-xs font-semibold uppercase tracking-wider text-brand-blue">Your primary machine</p>
                <p class="text-xs text-brand-slate -mt-3">
                    The machine you'll most often raise service tickets for. You can register more machines
                    later from your profile.
                </p>

                <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
                    <div>
                        <x-input-label for="primaryBrand" :value="__('Brand')" />
                        <select wire:model="primaryBrand" id="primaryBrand" class="mt-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                            <option value="">{{ __('Select brand') }}</option>
                            @foreach(['Mindray', 'Sysmex', 'Horiba', 'Abbott', 'Siemens', 'Beckman Coulter', 'Roche', 'Diatron', 'Philips'] as $b)
                                <option value="{{ $b }}">{{ $b }}</option>
                            @endforeach
                        </select>
                        <x-input-error :messages="$errors->get('primaryBrand')" class="mt-2" />
                    </div>
                    <div>
                        <x-input-label for="primaryModel" :value="__('Model')" />
                        <x-text-input wire:model="primaryModel" id="primaryModel" class="mt-2" type="text" name="primaryModel" required autocomplete="off" placeholder="e.g. BC-6800, XN-550" />
                        <x-input-error :messages="$errors->get('primaryModel')" class="mt-2" />
                    </div>
                    <div>
                        <x-input-label for="primarySerial" :value="__('Serial number (optional)')" />
                        <x-text-input wire:model="primarySerial" id="primarySerial" class="mt-2" type="text" name="primarySerial" autocomplete="off" placeholder="e.g. SN-001" />
                        <x-input-error :messages="$errors->get('primarySerial')" class="mt-2" />
                    </div>
                    <div>
                        <x-input-label for="primaryNickname" :value="__('Nickname (optional)')" />
                        <x-text-input wire:model="primaryNickname" id="primaryNickname" class="mt-2" type="text" name="primaryNickname" autocomplete="off" placeholder="e.g. Hematology main" />
                        <x-input-error :messages="$errors->get('primaryNickname')" class="mt-2" />
                    </div>
                </div>
            </div>

            {{-- ───────  Equipment: secondary machine (optional)  ─────── --}}
            <div class="rounded-xl bg-brand-cream/60 p-4 space-y-4 ring-1 ring-brand-mist/60">
                <p class="text-xs font-semibold uppercase tracking-wider text-brand-blue">A second machine (optional)</p>
                <p class="text-xs text-brand-slate -mt-3">
                    If you have another machine on site, register it here so it's ready to pick from
                    when you raise a ticket.
                </p>

                <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
                    <div>
                        <x-input-label for="secondaryBrand" :value="__('Brand')" />
                        <select wire:model="secondaryBrand" id="secondaryBrand" class="mt-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                            <option value="">{{ __('Select brand (optional)') }}</option>
                            @foreach(['Mindray', 'Sysmex', 'Horiba', 'Abbott', 'Siemens', 'Beckman Coulter', 'Roche', 'Diatron', 'Philips'] as $b)
                                <option value="{{ $b }}">{{ $b }}</option>
                            @endforeach
                        </select>
                        <x-input-error :messages="$errors->get('secondaryBrand')" class="mt-2" />
                    </div>
                    <div>
                        <x-input-label for="secondaryModel" :value="__('Model')" />
                        <x-text-input wire:model="secondaryModel" id="secondaryModel" class="mt-2" type="text" name="secondaryModel" autocomplete="off" placeholder="e.g. IntelliVue MX450" />
                        <x-input-error :messages="$errors->get('secondaryModel')" class="mt-2" />
                    </div>
                    <div>
                        <x-input-label for="secondarySerial" :value="__('Serial number (optional)')" />
                        <x-text-input wire:model="secondarySerial" id="secondarySerial" class="mt-2" type="text" name="secondarySerial" autocomplete="off" placeholder="e.g. SN-002" />
                        <x-input-error :messages="$errors->get('secondarySerial')" class="mt-2" />
                    </div>
                    <div>
                        <x-input-label for="secondaryNickname" :value="__('Nickname (optional)')" />
                        <x-text-input wire:model="secondaryNickname" id="secondaryNickname" class="mt-2" type="text" name="secondaryNickname" autocomplete="off" placeholder="e.g. Bedside" />
                        <x-input-error :messages="$errors->get('secondaryNickname')" class="mt-2" />
                    </div>
                </div>
            </div>

            <x-primary-button class="w-full justify-center" wire:loading.attr="disabled" wire:target="register">
                <span wire:loading.remove wire:target="register">{{ __('Create my account') }}</span>
                <span wire:loading wire:target="register" class="inline-flex items-center gap-2">
                    <svg class="h-4 w-4 animate-spin" viewBox="0 0 24 24" fill="none">
                        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z"></path>
                    </svg>
                    {{ __('Creating account…') }}
                </span>
            </x-primary-button>
        </form>

        <p class="mt-6 text-center text-sm text-brand-slate">
            {{ __('Already have an account?') }}
            <a href="{{ route('login') }}" wire:navigate
               class="font-semibold text-brand-blue hover:text-brand-blue-3 underline-offset-2 hover:underline">
                {{ __('Sign in') }}
            </a>
        </p>
    @endif
</div>
